### ISSUE TITLE
Issues with IBM Cloud object storage plug-in for CoreOS nodes

### ISSUE THREAD

**Issue by hfwen0502** [IBM/ibmcloud-object-storage-plugin#110]
We have set up an OpenShift cluster and the host OS is CoreOS-based. When testing it with the IBMCLOUD object storage plugin, the mount point to the COS bucket inside the pod can not see any file.

```
root@10 nccl-tests]# oc get pvc
NAME              STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
hf1-pvc-cos       Bound         pvc-eb8d2412-f317-4c90-9f27-37f92cbde5d7   200Gi      RWO            ibmc-s3fs-cos-perf           40m

[root@10 nccl-tests]# oc rsh fix-permission bash
root@fix-permission:/home/mpiuser# ls -alrt /data
total 0
drwxr-x---. 2 root root  6 Apr 19 15:05 .
dr-xr-xr-x. 1 root root 73 Apr 19 15:06 ..
```

Even though the PVC is created successfully, the fix-permission pod only sees an empty /data directory. Below is the pod manifest file:
```
apiVersion: v1
kind: Pod
metadata:
  name: fix-permission
  namespace: default
spec:
  imagePullSecrets:
  - name: all-icr-io
  containers:
  - name: fix-permission
    image: icr.io/hfwen/cuda-mpi-nccl-base:v2
    command: ['tail', '-f', '/dev/null']
    volumeMounts:
    - mountPath: "/data"
      name: cos-volume
  volumes:
  - name: cos-volume
    persistentVolumeClaim:
      claimName: hf1-pvc-cos
```
