### ISSUE TITLE
expose stat cache expiration

### ISSUE THREAD

**Issue by lmsurpre** [IBM/ibmcloud-object-storage-plugin#12]
We have an application that uses the lastModifiedTime of a file to determine if its been updated since we last checked.  Unfortunately, on an object-store backed volume, it seems like the file stats are cached indefinitely and so it never sees the update.

1. Is it possible to set some kind of cache invalidation policy for the file stat cache?
I think I could force the behavior I want by setting the cache size to 0, or bypassing it by listing the directory/otherwise accessing the file, but I'm concerned about the performance.
I see that s3fs has a property called `stat_cache_expire` that might be able to help...is there some way to set it from ibmcloud-object-storage-plugin?  I don't see it mentioned at https://console.test.cloud.ibm.com/docs/containers/cs_storage_cos.html#install_cos ...

2. If this is not supported at present, is there some other recommended approach?  Maybe a cron job that touches the files on some schedule?

**Comment by lmsurpre** [comment]
> I think I could force the behavior I want by setting the cache size to 0
I tested my theory by attempting to set the `ibm.io/stat-cache-size` annotation to zero in my PVC, but it seems its expecting a string and not a number...is that right?
```$ k edit pvc fhir-config-pvc
error: persistentvolumeclaims "fhir-config-pvc" could not be patched: cannot convert int64 to string
You can run `kubectl replace -f /var/folders/mg/ch346nld45391zsh5062j97c0000gn/T/kubectl-edit-qyreb.yaml` to try this update again.```

**Comment by lmsurpre** [comment]
For now, I added a livenessProbe which invokes ls on the directory whose stats I want to refresh (every 2 seconds):
```
        livenessProbe:
          exec:
            command:
            - ls
            - -R
            - /path/i/want/to/refresh
          initialDelaySeconds: 30
          periodSeconds: 2
```
I think this will work OK, but being able to set the `stat-cache-expire` property via an annotation would be much better.

**Comment by nkkashyap** [comment]
@lmsurpre 
Hi Lee
Currently, the stat cache is set to default, no expiry.
Good suggestion, we will expose the `stat_cache_expire` under PVC annotation in the pvc spec. 
Regarding, setting `ibm.io/stat-cache-size` annotation to` 0`, set the value as string, like
`ibm.io/stat-cache-size: "0"`
Thanks -Neeraj

**Comment by lmsurpre** [comment]
I found an issue with my workaround at https://github.com/IBM/ibmcloud-object-storage-plugin/issues/12#issuecomment-452486990 ...kubernetes only lets you have a single liveness probe (and a single readiness probe).  Eager for that annotation to be supported :-)

**Comment by mssachan** [comment]
Working on the required code change.

**Comment by mssachan** [comment]
@lmsurpre I have raised PR for setting `stat_cache_expire` parameter through PVC annotation.
https://github.com/IBM/ibmcloud-object-storage-plugin/pull/15
Could you please verify your scenario and see if it works or if possible, could you share the actual scenario which you are testing?
Thanks.

**Comment by lmsurpre** [comment]
We're using the ibmcloud-object-storage-plugin through IKS...what is the easiest way to temporarilly switch to this branch and then switch back?

The scenario itself can be simulated like this:
1. Install the plugin on your cluster
2. Create a PVC with the appropriate annotations
    example:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-name
  annotations:
    ibm.io/auto-create-bucket: "false"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: bucketname
    ibm.io/secret-name: object-storage-secret
    ibm.io/stat-cache-expire: "1"
    volume.beta.kubernetes.io/storage-class: ibmc-s3fs-standard-perf-regional
    volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-s3fs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```
3. Create two pods and mount the claim on each one
4. exec to pod A and create a file on the volume, then run `stat` on the file and note the lastModified time
5. exec to pod B and edit the file
6. exec to pod A and run `stat` on the file again

actual:
prior to the `stat-cache-expire` setting, step 6 would show the lastModified time from step 4

expected:
after setting `state-cache-expire`, I expect step 6 to show the lastModified time from step 5 (after 1 second in my example above)
