### ISSUE TITLE
Error while loading shared libraries: libfuse.so.2

### ISSUE THREAD

**Issue by baal-lgln** [IBM/ibmcloud-object-storage-plugin#152]
IBM Kubernetes Cluster
Kubernetes Version: 1.29.9 (Node with Ubuntu 24)
ibm-object-storage-plugin: 2.2.32

Since updating our Kubernetes Nodes to Ubuntu 24 we get the following error in our container:

```
MountVolume.SetUp failed for volume "pvc-..." : 
mount command failed, status: Failure, reason: 
Error mounting volume: s3fs mount failed: s3fs: error while loading shared libraries: libfuse.so.2: 
cannot open shared object file: No such file or directory
```

The container stays in pending mode. The PVC however is bound.

Example PVC:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  labels:
    billingType: hourly
    region: eu-de
  annotations:
    ibm.io/add-mount-param: complement_stat,compat_dir
    ibm.io/auto-create-bucket: 'false'
    ibm.io/auto-delete-bucket: 'false'
    ibm.io/bucket: BUCKET_NAME
    ibm.io/endpoint: https://s3.direct.eu-de.cloud-object-storage.appdomain.cloud
    ibm.io/secret-name: s3-access-secret
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ibmc-s3fs-smart-perf-regional
```

**Comment by baal-lgln** [comment]
Problem still persists.
Also tested on a Cluster Node with Kubernetes version 1.31.1_1527 with Ubuntu 24.

PVC YAML:
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  annotations:
    ibm.io/add-mount-param: complement_stat,compat_dir
    ibm.io/auto-create-bucket: 'false'
    ibm.io/auto-delete-bucket: 'false'
    ibm.io/bucket: BUCKET_NAME
    ibm.io/endpoint: https://s3.direct.eu-de.cloud-object-storage.appdomain.cloud
    ibm.io/secret-name: SECRET_NAME
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-s3fs-smart-perf-regional
```
Status is bound and PersistentVolume is created, but the Pod will not start:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: pvc-size-test
      image: public.ecr.aws/docker/library/busybox:stable
      command: ['/bin/sh', '-c']
      args: ['while true; do du -sh /data; sleep 10;done']
      volumeMounts:
        - mountPath: '/data'
          name: data
      resources: {}
```
This still leads to the error `FailedMount` and a pod stuck in `ContainerCreating`:
```
MountVolume.SetUp failed for volume "pvc-3a8a9b35-75a5-4289-8aaa-fcd38143bcb3" : mount command failed, status:
Failure, reason: Error mounting volume: s3fs mount failed: s3fs: error while loading shared libraries: 
libfuse.so.2: cannot open shared object file: No such file or directory 
```

Just switching to Ubuntu 20 as the base OS for the Nodes resolves this error. 
Ubuntu 20 is deprecated and will soon stop to be be supported by IBM Kubernetes Clusters, we need a solution for this!
